[project]
name = "flet-code-editor-dsl"
version = "0.2.0"
description = "Flet code editor controls with a declarative Language DSL: syntax highlighting, error underlines and code folding"
readme = "README.md"
requires-python = ">=3.10"
license = "Apache-2.0"
authors = [
    { name = "obgwew" }
]
dependencies = [
    "flet>=0.85.2",
]

[dependency-groups]
dev = [
    "mkdocs",
    "mkdocs-material",
    "mkdocstrings[python]"
]

[project.urls]
Homepage = "https://github.com/obgwew/flet-code-editor-dsl"
Documentation = "https://github.com/obgwew/flet-code-editor-dsl"
Repository = "https://github.com/obgwew/flet-code-editor-dsl"
Issues = "https://github.com/obgwew/flet-code-editor-dsl/issues"

[tool.setuptools.package-data]
"flutter.flet_code_editor_dsl" = ["**/*"]

[tool.setuptools]
license-files = ["LICENSE"]

[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"
